EventAPP/Pages/EventsPages/Create.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace EventAPP.Pages.EventsPages
{
    public class CreateModel : PageModel
    {
        private IEventRepository _service;
        public CreateModel (IEventRepository service)
        {
            _service = service;
        }
        [BindProperty]
        [Required(ErrorMessage ="Must have an id ")]
        [Range (0,int.MaxValue, ErrorMessage = "Must not be negative")]
        public int Id { get; set; }
        [BindProperty]
        [Required(ErrorMessage ="Missing a name")]
        [StringLength (100,MinimumLength =2,ErrorMessage = "The name must be between 2 and 100 letters")]
        public string Name { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public DateTime Date { get; set; }
        [BindProperty]
        public int MaxTilmeld { get; set; }

        [BindProperty]
        public EventType EventSlags { get; set; }
        public List<EventType> EventsTyper { get; set; }

        public void OnGet()
        {
            EventsTyper = Enum.GetValues<EventType>().ToList();
        }
        public IActionResult OnPost ()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }
            
           
            Events ev = new Events(Id,Name,Description,Date,EventSlags, MaxTilmeld);
            _service.Create(ev);
            return RedirectToPage("Index");
        }
    }
}

EventAPP/Pages/EventsPages/CreateDrink.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class CreateDrinkModel : PageModel
    {
        private IDrinkRepository _repository;

        public CreateDrinkModel(IDrinkRepository repository)
        {
            _repository = repository;
        }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public string Name { get; set; }
        [BindProperty]
        public double Price { get; set; }
        [BindProperty]
        public int Quanity { get; set; }
        [BindProperty]
        public DrinkType Drinktype { get; set; }
        public List<DrinkType> DrinkTypes { get; set; }

        public void OnGet()
        {
        DrinkTypes = Enum.GetValues<DrinkType>().ToList();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Drinks drinks = new Drinks(Id, Drinktype, Name, Price, Quanity );
            _repository.CreateDrinks( drinks );
            return RedirectToPage("DrinkIndex");
        }
    }
}

EventAPP/Pages/EventsPages/CreateUser.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EventLib.model;

namespace EventAPP.Pages.EventsPages
{

    public class CreateUserModel : PageModel
    {
        private IUserRepository _userRepository;
        public CreateUserModel(IUserRepository service)
        {
            _userRepository = service;
        }
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Password { get; set; }
        [BindProperty]
        public bool IsAdmin { get; set; }
        public List<User> Users { get; set; }
        public void OnGet()
        {
            Users = _userRepository.GetAllUsers();
            IsAdmin = false;
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                Users = _userRepository.GetAllUsers();
                return Page();
            }

            User us = new User
            {
                Email = Email,
                IsAdmin = IsAdmin,
                Password = Password
            };

            _userRepository.CreateUser(us);
            return RedirectToPage("UserIndex");

        }
    }
}

EventAPP/Pages/EventsPages/Delete.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EventLib;
using EventLib.model;

namespace EventAPP.Pages.EventsPages
{
    public class DeleteModel : PageModel
    {
        private IEventRepository _service;

        public DeleteModel(IEventRepository service)
        {
            _service = service; 
        }

        public Events Events { get; set; }
        
        public void OnGet(int id)
        {
            Events = _service.GetById(id);
        }

        public IActionResult OnPostDelete(int id)
        {
            _service.Delete(id);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostRegret()
        {
            return RedirectToPage("Index");
        }
    }
}

EventAPP/Pages/EventsPages/DeleteDrink.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class DeleteDrinkModel : PageModel
    {
        private IDrinkRepository _reposdrink;
        public DeleteDrinkModel(IDrinkRepository reposdrink)
        {
            _reposdrink = reposdrink;
        }
        public Drinks Drink { get; set; }
        public void OnGet(int id)
        {
            Drink = _reposdrink.DeleteDrinks(id);
        }
        public IActionResult OnPostDeleter(int id)
        {
            _reposdrink.DeleteDrinks(id);
            return RedirectToPage("DrinkIndex");
        }


    }
}

EventAPP/Pages/EventsPages/DeleteUser.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class DeleteUserModel : PageModel
    {
        private IUserRepository _userRepository;

        public DeleteUserModel(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
        public User user { get; set; }
        public void OnGet(string email)
        {
            user = _userRepository.GetUserByEmail(email);
        }
        public IActionResult OnPostDeleteUser(string email)
        {
            _userRepository.DeleteUser(email);
            return RedirectToPage("UserIndex");
        }
    }
}

EventAPP/Pages/EventsPages/DrinkIndex.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class DrinkIndexModel : PageModel
    {
        private IDrinkRepository _drinkrepo;
        private IUserRepository _userRepository;

        public DrinkIndexModel(IDrinkRepository drinkrepo)
        {
            _drinkrepo= drinkrepo;
        }
        public bool IsAdmin { get; set; }
        public List<Drinks> alledrinks { get; set; }
        public void OnGet()
        {
            alledrinks = _drinkrepo.GetAllDrinks();
            _userRepository = SessionHelper.GetUser(HttpContext);
            IsAdmin = _userRepository.IsUserAdmin;
        }
    }
}

EventAPP/Pages/EventsPages/Edit.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EventLib;
using EventLib.model;
using System.Diagnostics.Tracing;
using System.ComponentModel.DataAnnotations;

namespace EventAPP.Pages.EventsPages
{
    public class EditModel : PageModel
    {
        private IEventRepository _service;

        [BindProperty]
        public Events Events { get; set; }
        [BindProperty]
        public EventType EventSlags { get; set; }
        public List<EventType> EventsTyper { get; set; }
        [BindProperty]
        public int MaxTilmeld { get; set; }


        public EditModel(IEventRepository service)
        {
            _service = service;
        }



        public IActionResult OnGet(int id)
        {
            Events = _service.GetById(id);
            EventsTyper = Enum.GetValues<EventType>().ToList();
            return Page();

        }
        public IActionResult OnPost(int id, Events events)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            events.EventSlags = EventSlags;
            _service.Update(id,events);
            return RedirectToPage("Index");
        }

    }
}

EventAPP/Pages/EventsPages/EditDrink.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics.Tracing;
using System.IO;

namespace EventAPP.Pages.EventsPages
{
    public class EditDrinkModel : PageModel
    {
        private IDrinkRepository _repodrink;
        [BindProperty]
        public Drinks Drink { get; set; }
        [BindProperty]
        public DrinkType Drinktype { get; set; }
        public List<DrinkType> DrinkTypes { get; set; }

        public EditDrinkModel(IDrinkRepository repodrink)
        {
            _repodrink = repodrink;
        }
        public IActionResult OnGet(int id)
        {
            Drink = _repodrink.GetDrinkById(id);
            DrinkTypes = Enum.GetValues<DrinkType>().ToList();
            return Page();

        }
        public IActionResult OnPost(int id, Drinks drink)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            drink.Drinktype = Drinktype;
            _repodrink.UpdateDrinks(id,drink);
            return RedirectToPage("DrinkIndex");
        }
    }
}

EventAPP/Pages/EventsPages/Index.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EventLib.model;

namespace EventAPP.Pages.EventsPages
{
    public class IndexModel : PageModel
    {
        private IEventRepository _service;
        private IUserRepository _userRepository;
        private ITilmeld _tilmeldrepo;
        
        public bool IsAdmin { get; set; }

        public IndexModel(IEventRepository service, ITilmeld tilmeldrepo)
        {
            _service = service;
            _tilmeldrepo = tilmeldrepo;
        }
        public List<Events> kommendeevents { get; set; }
        public void OnGet()
        {
            kommendeevents = _service.GetAll();
            _userRepository = SessionHelper.GetUser(HttpContext);
            IsAdmin = _userRepository.IsUserAdmin;
            
        }
        public int GetAntal(int id)
        {
            return _tilmeldrepo.AntalTilmeldte(id);
        }
    }
}

EventAPP/Pages/EventsPages/Index1.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class Index1Model : PageModel
    {
        private IUserRepository _userRepository;


        public bool IsUserAdmin
        {
            get
            {
                return _userRepository.IsUserAdmin;
            }
        }
        public string Email => _userRepository.UserName;

        public Index1Model()
        {
        }
        public IActionResult OnGet()
        {
            _userRepository = SessionHelper.GetUser(HttpContext);

            if (!_userRepository.IsLoggedIn)
            {
                return RedirectToPage("LogIn");
            }
            return Page();

        }
    }
}

EventAPP/Pages/EventsPages/LogIn.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace EventAPP.Pages.EventsPages
{
    public class LogInModel : PageModel
    {

        private IUserRepository _userRepository;

        public LogInModel(IUserRepository userrepo)
        {
            _userRepository = userrepo;

        }
        [BindProperty]
        [Required]
        [StringLength(50, MinimumLength =5, ErrorMessage = "Please enter your Email")]
        public string Email { get; set; }
        [BindProperty]
        [Required]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Please enter your password"), DataType(DataType.Password)]
        public string Password { get; set; }
        public void OnGet()
        {
            _userRepository = SessionHelper.GetUser(HttpContext);

        }

        public IActionResult OnPost()
        {
            _userRepository = SessionHelper.GetUser(HttpContext);
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if(!_userRepository.TjekLogInd(Email, Password))
            {
                return Page();
            }

            SessionHelper.SetUser(_userRepository, HttpContext);
            return RedirectToPage("Index");


        }




    }
}

EventAPP/Pages/EventsPages/LogOut.cshtml.cs
using EventAPP.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class LogOutModel : PageModel
    {
        private IUserRepository _userRepository;

        public LogOutModel(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
    
        public IActionResult OnGet()
        {
            _userRepository = SessionHelper.GetUser(HttpContext);
            _userRepository.UserLoggedOut();
            SessionHelper.SetUser(_userRepository, HttpContext);

            return RedirectToPage("Index");
        }
    }
}

EventAPP/Pages/EventsPages/Tilmeld.cshtml.cs
using EventAPP.services;
using EventLib.model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EventAPP.Pages.EventsPages
{
    public class TilmeldModel : PageModel
    {
        // we inject the service trough the constructer 
        public TilmeldModel(IUserRepository service, IEventRepository Eservices, ITilmeld tilmeldrepo)
        {
            _userRepository = service;
            _eventrepo = Eservices;
            _tilmeldRepo = tilmeldrepo;
        }
        private IEventRepository _eventrepo;
        private IUserRepository _userRepository;
        private ITilmeld _tilmeldRepo;

        [BindProperty]
        public int ID { get; set; }
        [BindProperty]
        public string UserName { get; set; }
        [BindProperty]
        public Tilmeld Tilmeld { get; set; }

        public int MaxTilmeld { get; set; }
        [BindProperty]
        public List<User> Tilmeldte { get; set; }


        public void OnGet(int id)
        {
            MaxTilmeld = _eventrepo.GetById(id).MaxTilmeld;
            ID = id;
            _userRepository = SessionHelper.GetUser(HttpContext);
            UserName = _userRepository.UserName;

        }
        public IActionResult OnPost(int id)
        {
            if (!ModelState.IsValid)
            {
                return Page();

            }
            MaxTilmeld = _eventrepo.GetById(id).MaxTilmeld;
            if (_tilmeldRepo.AntalTilmeldte(ID) + 1 <= MaxTilmeld)
            {
                Tilmeld tilmeld = new Tilmeld(UserName, ID);

                _tilmeldRepo.CreateTilmeld(tilmeld);

            }
            else
            {
                return RedirectToPage("Index");
            }


            return RedirectToPage("Index");
        }
    }
}

EventAPP/Pages/EventsPages/UserIndex.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EventLib.model;
using EventAPP.services;

namespace EventAPP.Pages.EventsPages
{
    public class UserIndexModel : PageModel
    {
        private IUserRepository _userRepository;
        


        public UserIndexModel(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
        [BindProperty]
        public List<User> Users { get; set; }
        public void OnGet()
        {
            Users = _userRepository.GetAllUsers();
            _userRepository = SessionHelper.GetUser(HttpContext);
            if (_userRepository.IsLoggedIn)
            {
                //_userRepository.IsUserAdmin;
                //_userRepository.IsLoggedIn;

            }

        }
    }
}

EventAPP/Pages/EventsPages/Create.cshtml
@page
@model EventAPP.Pages.EventsPages.CreateModel
@{
}
<h1> Create a new event  </h1>
<div class="row">
    <div class="col-md-6 ">
        <form method="post">
            <div class="form-group">

                <label asp-for="@Model.Id" class="control-label">Event Id</label><br>
                <input asp-for="@Model.Id" class="form-control"/><br>
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
                </div>

                <div class="form-group">    
                <label asp-for="@Model.Name" class="control-label">Event name</label><br>
                <input asp-for="@Model.Name" class="form-control" /><br>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                <label asp-for="@Model.Description" class="control-label">Event description</label><br>
                <input asp-for="@Model.Description" class="form-control" /><br>
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.EventSlags" class="control-label">Event type</label><br>
                    <select asp-for="EventSlags" class="form-control"><br>
                    @foreach(var eve in Model.EventsTyper)
                    {
                        <option value="@eve">@eve</option>
                    }
                    </select>
                </div><br>

                <div class="form-group">
                <label asp-for="@Model.Date" class="control-label">Event Id</label><br>
                <input asp-for="@Model.Date" class="form-control" /><br>
                <span asp-validation-for="@Model.Date" class="text-danger"></span>
                </div>
                 <div class="form-group">
                <label asp-for="@Model.MaxTilmeld" class="control-label">Max participant</label><br>
                <input asp-for="@Model.MaxTilmeld" class="form-control" /><br>
                <span asp-validation-for="@Model.MaxTilmeld" class="text-danger"></span>
                </div>



            <div class="form-group">
                <input type="submit" value="Opret et event" />
            </div>
        </form>
    </div>
</div>

EventAPP/Pages/EventsPages/CreateDrink.cshtml
@page
@model EventAPP.Pages.EventsPages.CreateDrinkModel
@{
}
<h1> Create a new drink  </h1>
<div class="row">
    <div class="col-md-6 ">
        <form method="post">
            <div class="form-group">

                <label asp-for="@Model.Id" class="control-label">Drink number</label><br>
                <input asp-for="@Model.Id" class="form-control" /><br>
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Drinktype" class="control-label">Type</label><br>
                <select asp-for="Drinktype" class="form-control">
                    <br>
                    @foreach (var eve in Model.DrinkTypes)
                    {
                            <option value="@eve">@eve</option>
                    }
                </select>
            </div><br>

            <div class="form-group">
                <label asp-for="@Model.Name" class="control-label">Name</label><br>
                <input asp-for="@Model.Name" class="form-control" /><br>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Price" class="control-label">Price</label><br>
                <input asp-for="@Model.Price" class="form-control" /><br>
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Quanity" class="control-label">Quanity</label><br>
                <input asp-for="@Model.Quanity" class="form-control" /><br>
                <span asp-validation-for="@Model.Quanity" class="text-danger"></span>
            </div>




            <div class="form-group">
                <input type="submit" value="Create a drink" />
            </div>
        </form>
    </div>
</div>

EventAPP/Pages/EventsPages/CreateUser.cshtml
@page
@model EventAPP.Pages.EventsPages.CreateUserModel
@{
}
<h1> Create a new User  </h1>
<div class="row">
    <div class="col-md-6 ">
        <form method="post">
            <div class="form-group">

                <label asp-for="@Model.Email" class="control-label">Email</label><br>
                <input asp-for="@Model.Email" class="form-control" /><br>
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.IsAdmin" class="control-label">Is Admin</label><br>
                <input asp-for="@Model.IsAdmin" type="checkbox" id="@Model.IsAdmin" name="IsAdmin" checked="@Model.IsAdmin"/>
                <span asp-validation-for="@Model.IsAdmin" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Password" class="control-label">Password</label><br>
                <input asp-for="@Model.Password" class="form-control" /><br>
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create User" />
            </div>
        </form>
    </div>
</div>

EventAPP/Pages/EventsPages/Delete.cshtml
@page
@model EventAPP.Pages.EventsPages.DeleteModel
@{
}
<h1> Delete a event</h1>

<form method="post">
    <div class="form-group">
        <input type="submit"value="Delete event"asp-page-handler="Delete" asp-route-id="@Model.Events.Id"class="btn btn-danger"/>
        <input type="submit" value="Regret" asp-page-handler="Regret" class="btn btn-outline-primary"/>
    </div>
</form>

EventAPP/Pages/EventsPages/DeleteDrink.cshtml
@page
@model EventAPP.Pages.EventsPages.DeleteDrinkModel
@{
}
<form method="post">
    <div class="form-group">
        <input type="submit"value="Delete drink"asp-page-handler="Deleter" asp-route-id="@Model.Drink.Id"class="btn btn-danger"/>
    </div>
</form>

EventAPP/Pages/EventsPages/DeleteUser.cshtml
@page
@model EventAPP.Pages.EventsPages.DeleteUserModel
@using EventLib.model;
@{
}
<h1> Delete User</h1>

<form method="post">
    <div class="form-group">
        <input type="submit"value="Delete User"asp-page-handler="DeleteUser" asp-route-id="@Model.user.Email"class="btn btn-danger"/>
    </div>
</form>

EventAPP/Pages/EventsPages/DrinkIndex.cshtml
@page
@using EventLib.model;
@model EventAPP.Pages.EventsPages.DrinkIndexModel
@{
}
<h1>
    Overview over all the drinks
</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Drink Type</th>
            <th>Name</th>
            <th>Price in kr</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var e in @Model.alledrinks)
        {
            <tr>
                <td>
                    @e.Id
                </td>
                <td>
                    @e.Drinktype
                </td>
                <td>
                    @e.Name
                </td>
                <td>
                    @e.Price
                </td>
                <td>
                    @e.Quanity
                </td>
                @if (Model.IsAdmin)
                {
                    <td>
                        <a asp-page="DeleteDrink" asp-route-id="@e.Id">Delete</a> | <a asp-page="EditDrink" asp-route-id="@e.Id">Edit</a>
                    </td>
                }

            </tr>
        }
    </tbody>
</table>
@if (Model.IsAdmin){
<p>
    <a asp-page="CreateDrink"> Create a drink</a>
</p>
}

EventAPP/Pages/EventsPages/EditDrink.cshtml
@page
@model EventAPP.Pages.EventsPages.EditDrinkModel
@{
}
<h1> Update a Drink  </h1>
<div class="row">
    <div class="col-md-6 ">
        <form method="post">
            <div class="form-group">

                <label asp-for="@Model.Drink.Id" class="control-label">Drink Id</label><br>
                <input asp-for="@Model.Drink.Id" class="form-control" /><br>
                <span asp-validation-for="@Model.Drink.Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Drinktype" class="control-label">Drink type</label><br>
                <select asp-for="Drinktype" class="form-control">
                    <br>
                    @foreach (var eve in Model.DrinkTypes)
                    {
                            <option value="@eve">@eve</option>
                    }
                </select>
            </div><br>

            <div class="form-group">
                <label asp-for="@Model.Drink.Name" class="control-label">Drink name</label><br>
                <input asp-for="@Model.Drink.Name" class="form-control" /><br>
                <span asp-validation-for="@Model.Drink.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Drink.Price" class="control-label">Drink Price</label><br>
                <input asp-for="@Model.Drink.Price" class="form-control" /><br>
                <span asp-validation-for="@Model.Drink.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Drink.Quanity" class="control-label">Quanaity</label><br>
                <input asp-for="@Model.Drink.Quanity" class="form-control" /><br>
                <span asp-validation-for="@Model.Drink.Quanity" class="text-danger"></span>
            </div>




            <div class="form-group">
                <input type="submit" value="Save" class. />
            </div>
        </form>
    </div>
</div>

EventAPP/Pages/EventsPages/Index.cshtml
@page
@using EventLib.model;
@model EventAPP.Pages.EventsPages.IndexModel
@{
    ViewData["Title"] = "Events";
}

<h1>Oversigt over kommende events</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Event type</th>
            <th>Date</th>
            <th>number of participants</th>
            <th>max participants</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var e in @Model.kommendeevents)
        {
        
          <tr>
                    <td>
                        @e.Id
                    </td>
                    <td>
                        @e.Name
                    </td>
                    <td>
                        @e.Description
                    </td>
                    <td>
                        @e.EventSlags
                    </td>
                    <td>
                        @e.Date
                    </td>
                    <td>
                        @Model.GetAntal(e.Id)
                    </td>
                    <td>
                        @e.MaxTilmeld
                    </td>
                @if (Model.IsAdmin == false)
                    @if(EventAPP.services.UserRepository.loggedin){
                {
                    <td>
                        <a asp-page="/EventsPages/Tilmeld" asp-route-id="@e.Id">tilmeld</a>
                    </td>
                }
                    }
                @if (Model.IsAdmin)
                {
                    <td>
                        <a asp-page="Delete" asp-route-id="@e.Id">Delete</a> | <a asp-page="Edit" asp-route-id="@e.Id">Edit</a>
                    </td>
                }


                    
               
            </tr>
   
        }
       
    </tbody>
</table>
@if(Model.IsAdmin){
<p>
    <a asp-page="Create">Opret et event</a>
</p>
}

EventAPP/Pages/EventsPages/Index1.cshtml
@page
@model EventAPP.Pages.EventsPages.Index1Model
@{
}

EventAPP/Pages/EventsPages/LogIn.cshtml
@page
@model EventAPP.Pages.EventsPages.LogInModel
@{

}
<div class="center-screen">
    <div class="row wrapper">
        <h2>Login</h2>
        <div class="col-md-4">
            <form method="post">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <div class="form-group box">
                    <span class="icons"><ion-icon name="mail-sharp"></ion-icon></span>
                    <label asp-for="@Model.Email" class="control-label">Email</label><br>
                    <div class="textp">
                    <input asp-for="@Model.Email" class="form-control" /><br>
                    </div>
                    <span asp-validation-for="@Model.Email" class="text-danger"></span>
                </div>
                <div class="form-group box">
                    <span class="icons"><ion-icon name="lock-closed-sharp"></ion-icon></span></span>
                    <label asp-for="@Model.Password" class="control-label">Password</label><br>
                    <input type="password" asp-for="@Model.Password" class="form-control" /><br>
                    <span asp-validation-for="@Model.Password" class="text-danger rød"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Sign in" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

EventAPP/Pages/EventsPages/LogOut.cshtml
@page
@model EventAPP.Pages.EventsPages.LogOutModel
@{
}